export { default as Setting } from './setting.svg';
export { default as Sort } from './sort.svg';
export { default as Home } from './home.svg';
export { default as Asterisk } from './asterisk.svg';
export { default as Sparkle } from './sparkle.svg';
export { default as Sparkles } from './sparkles.svg';
export { default as Dot } from './dot.svg';
export { default as OutlinedCircle } from './outlined-circle.svg';
export { default as WorldGrid } from './world-grid.svg';

// Logos;
export { default as Eslint } from './logos/eslint.svg';
export { default as Git } from './logos/git.svg';
export { default as GraphQL } from './logos/graphql.svg';
export { default as Javascript } from './logos/javascript.svg';
export { default as Jest } from './logos/jest.svg';
export { default as Mobx } from './logos/mobx.svg';
export { default as Nextjs } from './logos/nextjs.svg';
export { default as Prettier } from './logos/prettier.svg';
export { default as ReactQuery } from './logos/react-query.svg';
export { default as React } from './logos/react.svg';
export { default as Redux } from './logos/redux.svg';
export { default as Sass } from './logos/sass.svg';
export { default as Styled } from './logos/styled.svg';
export { default as Stylex } from './logos/stylex.svg';
export { default as Tailwind } from './logos/tailwind.svg';
export { default as Typescript } from './logos/typescript.svg';
export { default as Vite } from './logos/vite.svg';
